### ISSUE TITLE
Automate accepting stanek's gift and include in autopilot.js

### ISSUE THREAD

**Issue by alainbryden** [alainbryden/bitburner-scripts#105]

**Comment by Evanito** [comment]
In BN8 with SF13.1, you get a 2x3 Stanek grid. Since there is no currently set layout for this, the script buys Genesis (-10%) then does nothing. 😢  
- Maybe include a check for if we have a valid layout before continuing stanek.js? 
- Or have trivial solutions for low grid sizes (I think 2x3 is the lowest possible size)
  - Is it even worth it?

**Comment by alainbryden** [comment]
I didnt recall it going this small. I can add something.

It is worthwhile, as long as the stat you're boosting is the most important
one to you. You can e.g. get a 50% boost to hacking or rep gain rates,
you're just (initially) sacrificing a bit of every other stat.

**Comment by alainbryden** [comment]
Fixed with https://github.com/alainbryden/bitburner-scripts/commit/a2b81b0483e63d3fd758d2eb3418e5672331c805
And with that, I'll probably close this ticket, because stanek is about as fleshed out as it can be.
