### ISSUE TITLE
suggestion: give some examples for configs

### ISSUE THREAD

**Issue by Dragonlord1005** [alainbryden/bitburner-scripts#113]
Specifically using some of the aliases you use, like a daemon config for the start command for example

**Comment by alainbryden** [comment]
I put some fake examples in the readme, but I would be hard pressed to come up with real world examples that I would use, because they aren't for me :) 

When I personally want to permanently change the default configuration of a script, I just change the source code, but for folks that want their own permanent defaults and don't want to manage their own fork or resolve conflicts on every pull, this is a way to do that now. Hope that makes sense.
