### ISSUE TITLE
Rapid Early Progression

### ISSUE THREAD

**Issue by Thedakdragon** [alainbryden/bitburner-scripts#128]
I've noticed, especially once you get SF4.1, that the best way to progress the VERY early game is to;
Spam Mug til you have ~ 250k
Kill all Scripts
Run Casino til Kicked Out
Buy all the RAM
Soft Reset
Repeat Once more
then Soft Reset and Start auto pilot/Daemon
It takes about 30 min or so but get you up to the 2TB ram, which drastically speeds up getting REP early game.
Anyway to make this a script that could run on 4/32gbs or is it completely SF4 dependent?
Something like checks your ram and if its under 2TB runs Crime.js until money is 250k, then kills and runs Casino.js?

**Comment by alainbryden** [comment]
This used to be something these scripts automated as well, but not any more because it soon no longer is optimal to reset early on like that.

Without giving too many spoilers away, there is a source file which gives you a significant boost in your **first reset only** of a new augmentation. After you install augmentations (or soft-reset), you lose that bonus, so it doesn't make sense to do it just so you can cheese casino.js twice.

You are definitely encouraged to use this strategy yourself though until you encounter what I'm talking about.

**Comment by alainbryden** [comment]
Also, if I understood your question correctly - yes, you would need SF4 if you wanted to automate doing crime or soft-resetting. Most of what my scripts automate requires SF4, so it's good that you're doing it early.
