### ISSUE TITLE
what dus this mean Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical. stack: TypeError: Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical.

### ISSUE THREAD

**Issue by maxballz** [alainbryden/bitburner-scripts#129]
Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical.

**Comment by maxballz** [comment]
this is on  autopilot.js

**Comment by alainbryden** [comment]
I think this happens when you manually put the scripts in a folder without using "git-pull.js".

git-pull.js has an argument that will rewrite all files as they are downloaded to fix the path if you are downloading them to a folder. The path `./helpers.js` only works if the helpers file is in the root of the repository.
