### ISSUE TITLE
autopilot.js: Use a better --enable-bladeburner heuristic

### ISSUE THREAD

**Issue by Evanito** [alainbryden/bitburner-scripts#137]
Currently, autopilot.js will only automatically enable bladeburner in BN6 and BN7. 
This leaves it up to the user to decide to enable it in other Bitnodes despite possibly not knowing if the Bitnode will require it for progression.

I suggest changing to either an expanded lists of Bitnodes with Bladeburner enabled or use a heuristic that estimates when the normal Hacking level --> Daedalus --> world_daemon path will be too slow.

### Hardcoded list solution
Suggested BNs: 6, 7, 9, 10
Other Bitnodes might require manual A/B testing

### Heuristic solution
Relevant factors might be:
- Hacking level multiplier (major factor)
- Daedalus hack requirement (minor factor)
- world_daemon hack requirement (major factor)

**Comment by alainbryden** [comment]
Interesting you think so. I found that even in BN 6 & 7, I was getting a hacking win before bladeburner, I just stuck it in there because surely people are actually interested in exploring the mechanic instead of ignoring entirely.

I honestly believe there isn't a single situation (except perhaps very high levels of BN12) in which a bladeburner win can feasibly come before a hacking win.

**Comment by alainbryden** [comment]
I'll leave this issue open though until I've had a chance to prove the point. I'll open up two instances of chrome, one private, start BN 10 at the same time, one with bitburner enabled, see what finishes first.

**Comment by alainbryden** [comment]
More or less fixed with https://github.com/alainbryden/bitburner-scripts/commit/da545d41084d0df4b3c8768758b2eb01fa19b562
It seems obvious, but daemon.js just needs to launch bladeburner.js if the player has already joined bladeburner (one time manual intervention). That takes care of all resets until the next install.

Besides that, I'll wait until the sleeves+bladeburner feature is released before I decide whether it's worthwhile activating bladeburner by default in all nodes.
