### ISSUE TITLE
hacknet-upgrade-manager.js: hack node money mult seems to ignore bitnode multiplier

### ISSUE THREAD

**Issue by ProjectYoung** [alainbryden/bitburner-scripts#155]
Line 68 doesn't take bitnode multiplier into account, is it intentional?

**Comment by alainbryden** [comment]
It is intentional.

If you look at the source code for the formulas API `ns.formulas.hacknetServers.hashGainRate` function that I'm using on line 95:
https://github.com/danielyxie/bitburner/blob/master/src/Hacknet/formulas/HacknetServers.ts#L4
![image](https://user-images.githubusercontent.com/2285037/170500615-417b6d51-247a-4225-a58b-3638842fc1d0.png)
You will see that the game already applies the bitnode multiplier for us, so for us to include it in the "currentHacknetMult" would result in it being double-applied.


In the "fallback-approach" used when the player doesn't have Formulas.exe, we don't even need these multipliers, because we ask the node itself what its current production is (`nodeStats.production`) which uses the same function behind-the-scenes. (Note: the reason we don't use this approach by default is because it also includes the impact of any running scripts on node, which we *don't* want to see)
