### ISSUE TITLE
work-for-factions corporation job selection

### ISSUE THREAD

**Issue by EinzigeMeister** [alainbryden/bitburner-scripts#172]
bestJobTier only looks for IT/Software, which generally promote faster, except when combat skills accelerate significantly faster in certain bitnodes. 
Not sure if jobs that don't offer security work complicates things or if me manually adding augs throughout the BN just made me more combat biased. Sleeves going on their killing sprees also greatly contributes to my combat stats.

(Currently in BN9.3, getting 88 rep/sec as a software engineer where security offers 340 rep/sec for Megacorp)

**Comment by alainbryden** [comment]
You're right that rep can be earned faster if you manually prioritize physical augs, but the code doesn't do that. If you check out the code for working for megacorporations, it is quite complicated just codifying the optimal "hack" career path - complicated enough that I did not feel it was worthwhile to attempt other combat-based paths, especially since my algorithms never encounter that path on their own (e.g. without manual intervention).

I would say that if you want to manually progress the game, there are certainly things that you can do to move things along faster based on your individual suggestion, and I would recommend killing work-for-faction.js and autopilot.js while you're doing them. Those tools are more for going AFK for long periods of time.

**Comment by EinzigeMeister** [comment]
That makes sense from when I was looking at the code and is what I’ve been doing. Thanks for taking the time to respond.
