### ISSUE TITLE
 hacknet-upgrade-manager.js

### ISSUE THREAD

**Issue by Kitzune** [alainbryden/bitburner-scripts#181]
hacknet-upgrade-manager.js ignores the "--max-payoff-time" argument.
Either as argument or as config it gets overwritten
The reason could be line 253 in the daemon.js

**Comment by kotenok2000** [comment]
hacknet script runs with arguments 

Args: ["-c", "--max-payoff-time", "4h", "--max-spend", 2669297537.8726387]

**Comment by alainbryden** [comment]
You're looking at the wrong instance. Bitburner allows many instances of the same script to run with different arguments. Use the ps terminal command to see all running script instances.

**Comment by Kitzune** [comment]
True that Bitburner allows multiple instances to run. But the hacknet-upgrade-manager.js did have only 1 instances running.
If i run Daemon.js it is overwriting the setting i have in hacknet-upgrade-manager.js.config.txt or change i did in hacknet-upgrade-manager.js.
Maybe that is intentionally?

**Comment by alainbryden** [comment]
Yeah, it's intended. The config is only for setting the default value of args when they are not otherwise specified. Daemon launches 3 versions of the hacknet upgrade manager for different points in the ascension. If you want to specify a specific max-payoff-time, try setting it up as an alias and running as needed.
