### ISSUE TITLE
Gang issues 

### ISSUE THREAD

**Issue by Eugney** [alainbryden/bitburner-scripts#19]
Still very new to javascript 
When I try to run Gangs.js I get 
ns.read('/Temp/gang-augs.txt') somehow returned undefined or an empty string
I've looked all through gangs.js and into the temp file created there are no issues that i can figure out i don't know if its me or just an actual error just wanted to give a heads up

**Comment by doug-w** [comment]
This looks like a call to **getAugmentationsFromFaction**(facName)

From the docs:

_If you are not in BitNode-4, then you must have Level 3 of Source-File 4 in order to use this function.

Returns an array containing the names (as strings) of all Augmentations that are available from the specified faction. The argument must be a string with the faction's name. This argument is case-sensitive._

**Comment by Eugney** [comment]
Strange i dont have level 3 of the SF4 but i am in BN4

**Comment by Eugney** [comment]
Remove everything i said i was in BN 2 lol im an idiot sorry for the trouble
