### ISSUE TITLE
Request to suppress errors/warnings about missing SF functionality

### ISSUE THREAD

**Issue by archraziel** [alainbryden/bitburner-scripts#2]
Is possible to run you script and make it ignore the fact that I dont have bitnodes and source files?
When I run daemon.js I get a lot of errors popping.

I made the files list to download on the first time git-pull.js is called to download all the files from the repo
Tried to get the file automatically inside the game but I dont think is possible right now.

"/Flags/deleting.txt",
"/Remote/grow-target.js",
"/Remote/hack-target.js",
"/Remote/manualhack-target.js",
"/Remote/weak-target.js",
"/Tasks/backdoor-all-servers.js",
"/Tasks/backdoor-all-servers.js.backdoor-one.js",
"/Tasks/contractor.js",
"/Tasks/contractor.js.solver.js",
"/Tasks/program-manager.js",
"/Tasks/ram-manager.js",
"/Tasks/run-with-delay.js",
"/Tasks/tor-manager.js",
"/Tasks/write-file.js",
"analyze-hack.js",
"cascade-kill.js",
"cleanup.js",
"crime.js",
"daemon.js",
"faction-manager.js",
"farm-intelligence.js",
"gangs.js",
"get-list.js",
"git-pull.js",
"hacknet-upgrade-manager.js",
"helpers.js",
"host-manager.js",
"remove-worst-server.js",
"reserve.js",
"reserve.txt",
"run-command.js",
"scan.js",
"sleeve.js",
"spend-hacknet-hashes.js",
"stats.js",
"stockmaster.js",
"work-for-factions.js"

**Comment by alainbryden** [comment]
Thanks for the list. I didn't want to hard-code it in the script itself because my intent is for people to use it with their own repositories, and I didn't see an easy way to get a repository listing from github, so I have it as a "TODO" in there.

As for the other request, sadly letting errors happening, and catching them, is the "best" way to detect functionality missing due to the current BN or missing SF files, because the actual ns function to check the current BN or player owned SF files costs RAM, and I've been trying to keep daemon RAM quite low. I'll try to tweak it over time to be less noisy about the functions that it can't access - I know it's annoying.

**Comment by archraziel** [comment]
I was thinking. Instead of checking if the player has SF files and making . Is it possible to use an arg to tell the code to run without SF functions? Or even args for each SF, so the player can say which one he already owns?

**Comment by alainbryden** [comment]
Yeah, that's totally reasonable. I'll come with args to turn them off
preemptively

**Comment by alainbryden** [comment]
Did a chunk of work on this today. Prioritized turning crashes into errors and intentional shutdowns where necessary, but haven't gotten rid of all alerts yet, so leaving this open until it's cleaner

**Comment by archraziel** [comment]
Nice, thank you very much!

**Comment by alainbryden** [comment]
Should be better now.

I imagine by now you've fixed all this yourself and no longer want to bother pulling / merging with your own changes, but it should help the next guy getting started
