### ISSUE TITLE
Subfolders prevents daemon from starting

### ISSUE THREAD

**Issue by pabluuz** [alainbryden/bitburner-scripts#23]
### Problem:
When **using subfolders**, I'm **unable to start daemon**
![image](https://user-images.githubusercontent.com/10631173/147994778-5e18bff0-f7e3-4165-a2a2-54bbee8cb3d5.png)

> RUNTIME ERROR
> /alain/daemon.js@home
> 
> Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical.
> stack:
> TypeError: Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical.
> 

Looks like relative url is valid, I coudn't find any more information how to fix this

### Reproduce:
1. set in git-pull.js:
`['subfolder', '/alain']`
2. `run /alain/daemon.js`

### More info:
Scripts downloaded to correct directory, and they are there
![image](https://user-images.githubusercontent.com/10631173/147994910-f8e48a99-b8be-49de-bf6f-71a64c3eafec.png)
I've also tried to run it by 
```
cd alain  
run daemon.js
```
alas to no avail

**Comment by alainbryden** [comment]
I just wanted you to know that I accept that this is an issue for other folks, and it's unfortunately a tricky thing to test and get working throughout. I believe every script that users "helpers" (most of them) is using a "relative to root" path rather than a "relative to the current directory" path and it would take quite a bit of testing / changes to get them all right.

If anyone works through this and gets it all fixed with paths that work both from a folder and from root, please do make a pull request. If not, it's a low priority (because it doesn't affect me), but I will eventually attempt to get this fixed.
