### ISSUE TITLE
faction-manager.js: "Shadows of Anarchy" issues in faction-manager

### ISSUE THREAD

**Issue by arielsalvo** [alainbryden/bitburner-scripts#235]
"Shadows of Anarchy" presents some issues for the faction manager:

1. They don't accept donations so, maybe add them to the `factionsWithoutDonation` [list](https://github.com/alainbryden/bitburner-scripts/blob/3fb917a4cc9a95606fac50876f6dabe729137961/faction-manager.js#L18)? 
1. Also, the rep required to buy their augs keeps increasing so, after getting a membership, the logic breaks. I added `SoA - phyzical WKS harmonizer` to the `priority-aug` list and the rest to the `omit-aug` list in my config.

**Comment by alainbryden** [comment]
You're free to configure faction manager to your liking, but I won't code them into my scripts because there is no automation for infiltration in my scripts. You would have to manually Infiltrate and therefore manually manage their augs - which as you said don't follow the same pricing rules as any other augs, so doesn't work  with this script.
