### ISSUE TITLE
Factions: Shadows of Anarchy

### ISSUE THREAD

**Issue by doubravap** [alainbryden/bitburner-scripts#242]
ascend.js (autopilot.js) does not buy augmentation from this faction.
First need buy "SoA - phyzical WKS harmonizer". Other augmentation buy random

**Comment by alainbryden** [comment]
Sorry, this won't change. Others have specifically requested I ignore this faction, because buying its augs can interfere with infiltration scripts. Also, their aug prices are all interlinked and its an annoying special case to code for. Finally, they faction doesn't even appear unless you play manually, and autopilot is only optimized for automated play, not manual play.
