### ISSUE TITLE
When casino.js runs it sometimes drops into cloud save conflict page

### ISSUE THREAD

**Issue by kotenok2000** [alainbryden/bitburner-scripts#249]
And  when i press take me back it says "casino.js: ERROR: Could not find one or more game controls. Did something steal focus? Trying again... Please post a full-game screenshot on Discord if you can't get past this point."

![image](https://user-images.githubusercontent.com/8822292/209556302-aad84b2e-e279-4b48-a284-6153a59e95e7.png)
![image](https://user-images.githubusercontent.com/8822292/209556407-b78c0eea-c6c5-4add-b5ad-be5cd9e936fd.png)

**Comment by alainbryden** [comment]
The first screenshot is something you should take to the game's discord. If your current game really is the one on the left (51 days playtime) then it's highly suspicious that the steam cloud has a saved game with 201 days it's trying to load when you reboot the game.

Casino.js only "highlights" this issue because it rapidly saves / reloads the game (by design).

When the above "save conflict" stops appearing, casino.js will start working normally, so the former is the core issue that you need to resolve.

**Comment by kotenok2000** [comment]
I have imported browser save over steam one.

**Comment by alainbryden** [comment]
I would expect that the first time you shut down the game though, your new save gets uploaded to the steam cloud and replaces the old one.
