### ISSUE TITLE
2.2.0 stats.js

### ISSUE THREAD

**Issue by dracomalar93** [alainbryden/bitburner-scripts#253]
I am experiencing the following error when stats.js is run:

WARNING: stats.js Caught (and suppressed) an unexpected error in the main loop. Update Skipped: ns.read('/Temp/getServers.txt') returned a bad result: "ERROR: ns.getServer called with no this value. ns functions must be bound to ns if placed in a new variable. e.g. const getServer = ns.getServer.bind(ns); getServer("home",0,["home","daemon-4","daemon-3","daemon-2","daemon-1","daemon-0","daemon","daemon-23","daemon-22","daemon-21","daemon-20","daemon-19","daemon-18","daemon-17","daemon-16","daemon-15","daemon-14","daemon-13","daemon-12","daemon-11","daemon-10","daemon-9","daemon-8","daemon-7","daemon-6","darkweb","iron-gym","nectar-net","phantasy","the-hub","catalyst","lexo-corp","summit-uni","aevum-police","snap-fitness","harakiri-sushi","max-hardware","neo-net","netlink","I.I.I.I","hong-fang-tea","zer0","silver-helix","johnson-ortho","computek","joesguns","sigma-cosmetics","foodnstuff","CSEC","omega-net","avmnite-02h","syscore","millenium-fitness","rho-construction","zb-institute","alpha-ent","global-pharm","aerocorp","deltaone","zeus-med","icarus","defcomm","taiyang-digital","applied-energetics","stormtech","kuai-gong","omnitek","clarkinc","blade","b-and-a","megacorp","ecorp","galactic-cyber","unitalife","solaris","nova-med","titan-labs","vitalife","4sigma","infocomm","microdyne","fulcrumtech",".","powerhouse-fitness","fulcrumassets","nwo","The-Cave","univ-energy","zb-def","run4theh111z","helios","omnia","rothman-uni","crush-fitness","n00dles"]); ". Script: /Temp/getServers.txt.js Args: ["home","daemon-4","daemon-3","daemon-2","daemon-1","daemon-0","daemon","daemon-23","daemon-22","daemon-21","daemon-20","daemon-19","daemon-18","daemon-17","daemon-16","daemon-15","daemon-14","daemon-13","daemon-12","daemon-11","daemon-10","daemon-9","daemon-8","daemon-7","daemon-6","darkweb","iron-gym","nectar-net","phantasy","the-hub","catalyst","lexo-corp","summit-uni","aevum-police","snap-fitness","harakiri-sushi","max-hardware","neo-net","netlink","I.I.I.I","hong-fang-tea","zer0","silver-helix","johnson-ortho","computek","joesguns","sigma-cosmetics","foodnstuff","CSEC","omega-net","avmnite-02h","syscore","millenium-fitness","rho-construction","zb-institute","alpha-ent","global-pharm","aerocorp","deltaone","zeus-med","icarus","defcomm","taiyang-digital","applied-energetics","stormtech","kuai-gong","omnitek","clarkinc","blade","b-and-a","megacorp","ecorp","galactic-cyber","unitalife","solaris","nova-med","titan-labs","vitalife","4sigma","infocomm","microdyne","fulcrumtech",".","powerhouse-fitness","fulcrumassets","nwo","The-Cave","univ-energy","zb-def","run4theh111z","helios","omnia","rothman-uni","crush-fitness","n00dles"] Command: ns.args.map(ns.getServer) The script was likely passed invalid arguments. Please post a screenshot of this error on discord.

Currently trying to figure out this one

**Comment by ashugar** [comment]
so, back to the original post, the error is due to ns.getServer not being bound to "this" within the game's code.  To do this, you'll need to add the following at the top of the main function (I put it right after `disableLogs(ns, ['sleep']);`):
`const getPlayer = ns.getPlayer.bind(ns); // V2.2 Update`

Then you need to look further down for this line:
`playerInfo = await getNsDataThroughFile(ns, ns.getPlayer(), '/Temp/getPlayer.txt');`
Change to:
`playerInfo = await getNsDataThroughFile(ns, getPlayer, '/Temp/getPlayer.txt'); // V2.2 Update`

Now look a few lines further down for this:
`(playerInfo = await getNsDataThroughFile(ns, ns.getPlayer(), '/Temp/getPlayer.txt')).inBladeburner;`
Change to:
`(playerInfo = await getNsDataThroughFile(ns, getPlayer, '/Temp/getPlayer.txt')).inBladeburner; // V2.2 Update`

New item to update is this:
`const sharePower = await getNsDataThroughFile(ns, ns.getSharePower(), '/Temp/getSharePower.txt');`
Change to:
`const getSharePower = ns.getSharePower.bind(ns); // V2.2 Update`
`const sharePower = await getNsDataThroughFile(ns, getSharePower, '/Temp/getSharePower.txt');`

New item to update is this:
`const reserve = Number(ns.read("reserve.txt") || 0);`
Change to:
`const read = ns.read.bind(ns); // V2.2 Update`
`const reserve = Number(read("reserve.txt") || 0);`

There are going to be additional issues stemming from this into the helper.js script, but that should resolve the issues that reside in stats.js (at least until helpers.js is updated).

As it stands, stats.js is unusable with these changes.  If someone fixes that before someone that works on this repository fixes it, great! Otherwise, you'll have to kill the script when it runs as it doesn't report properly.

**Comment by alainbryden** [comment]
This ticket is now obsolete since the game reverted the API breaks regarding requiring `bind`.
