### ISSUE TITLE
daemon.js error after remove-worst-server

### ISSUE THREAD

**Issue by fsteveb** [alainbryden/bitburner-scripts#263]
I am getting this error in the latest code.
`host-manager.js: SUCCESS: Purchased a new server daemon-9 with 524,288 GB RAM for $66.243b
remove-worst-server.js: Deleted daemon-10 which had 8,192 GB of RAM (23 servers remaining).
daemon.js: INFO: The server "daemon-10

Stack:
daemon.js:L897@Server.getSecurity
daemon.js:L907@Server.isPrepped
daemon.js:L-1@unknown
daemon.js:L1799@_sortServersAndReturn
daemon.js:L1826@getAllServersByTargetOrder" appears to have been deleted. Removing it from our lists
daemon.js: ERROR: Failed to find server with the name "daemon-10

Stack:
daemon.js:L897@Server.getSecurity
daemon.js:L907@Server.isPrepped
daemon.js:L-1@unknown
daemon.js:L1799@_sortServersAndReturn
daemon.js:L1826@getAllServersByTargetOrder" in the allHostNames list.
daemon.js: ERROR: Failed to find server by name "daemon-10

Stack:
daemon.js:L897@Server.getSecurity
daemon.js:L907@Server.isPrepped
daemon.js:L-1@unknown
daemon.js:L1799@_sortServersAndReturn
daemon.js:L1826@getAllServersByTargetOrder".`

**Comment by alainbryden** [comment]
It is expected behaviour that `remove-worst-server.js` can delete a server right as `daemon.js` goes to use it. Previously, I've caught the error and suppressed it - but the way I do that is by searching for a specific string in the error message. Any time a game update slightly changes that error message, it stops matching though, and the error becomes "noisy".

So I'll leave this ticket open to make sure I update the expected error message so I can silence it again, but rest assured it's an "expected" error and is handled normally.

It would be helpful if you can provide me with a screenshot of the error. The copy-pasted text above is mixed up because you the game's tail windows are split across multiple html elements, they don't get written to the clipboard in a straightforward way.

**Comment by fsteveb** [comment]
I hadn't seen this error before so I figured it was new and you might want to hear about it. I'm glad it's not a new issue and already has a fix. It happened again so I got a screen shot this time. I hope it helps.

![daemonerror](https://user-images.githubusercontent.com/1929691/211361549-b85c4c22-d316-4041-9005-62b3f3dfde5a.png)
