### ISSUE TITLE
Runtime Error in Daemon

### ISSUE THREAD

**Issue by WiseMack** [alainbryden/bitburner-scripts#265]
RUNTIME ERROR
/alain/daemon.js@home (PID - 5)

CONCURRENCY ERROR
/alain/daemon.js@home (PID - 92)

getServerMaxRam: Concurrent calls to Netscript functions are not allowed!
      Did you forget to await hack(), grow(), or some other
      promise-returning function?
      Currently running: sleep tried to run: getServerMaxRam

Stack:
/alain/daemon.js:L271@reqRam
/alain/daemon.js:L274@Object.shouldRun
/alain/daemon.js:L447@runStartupScripts
/alain/daemon.js:L356@Module.main

No idea what the problem is, just came back after leaving for a few hours, the screen was black, hit F5 and got this error.

**Comment by alainbryden** [comment]
This will be due to a bug in v2.2.1 of bitburner that allows two instances of the same script with the same arguments to be run.

If you reload the game (F5), all scripts that were running would get relaunched, but start over at the beginning. When autopilot starts over, it launch daemon.js with certain args, but that script is already running with those args. The game was silently suppressing that, but not anymore.

I have logic that would detect when daemon.js is relaunched with new args and shut down the old one, but it does nothing if both instances have the same args (which previously was impossible).

The bug is fixed in v2.2.2.
