### ISSUE TITLE
gangs.js doesn't create gang-augs.txt

### ISSUE THREAD

**Issue by Celebane** [alainbryden/bitburner-scripts#27]
![image](https://user-images.githubusercontent.com/15112037/148474039-79615270-d5f6-4caf-9009-85fd5bc705e1.png)

**Comment by eyoung100** [comment]
This is also happening with faction Manager

**Comment by alainbryden** [comment]
It would appear you're missing SF 4.3, which is required in both cases, but I'll work on adding a pre-emptive check so it's clear.

**Comment by Celebane** [comment]
Thanks!

**Comment by archraziel** [comment]
@alainbryden there was a rework on SF4...SF4.1 gives all functions but with 64 times the cost, sf4.2 is 8 times the cost and sf4.3 is 1 times.
For example work-for-faction on sf4.1 is now around 130gb memory to use.

**Comment by alainbryden** [comment]
Thanks, that'll explain lots of the issues early players are having.

**Comment by BasTijs** [comment]
I have 4.3 and just started 2.1, but almost all scripts give an error early game because of not enough RAM (currently 32G) due to read txt files.

work-for-factions.js: FAIL: (0 retries remaining): Run command returned no pid. Destination: /Temp/aug-stats.txt.js Command: let result = ""; 
.......
        if (ns.read("/Temp/aug-stats.txt") != result) await ns.write("/Temp/aug-stats.txt", result, 'w')
Ensure you have sufficient free RAM to run this temporary script.

daemon.js: FAIL: (0 retries remaining): Run command returned no pid. Destination: /Temp/sell-hashes-for-money.js Command: 0; if(ns.hacknet.spendHashes("Sell for Money")) ns.toast('Sold 4 hashes for $1M', 'success')
Ensure you have sufficient free RAM to run this temporary script.

daemon.js: WARNING: Caught an error in the targeting loop: Run command returned no pid. Destination: /Temp/sell-hashes-for-money.js Command: 0; if(ns.hacknet.spendHashes("Sell for Money")) ns.toast('Sold 4 hashes for $1M', 'success')
Ensure you have sufficient free RAM to run this temporary script.

host-manager.js: FAIL: (0 retries remaining): Run command returned no pid. Destination: /Temp/owned-source-files.txt.js Command: let result = ""; try { result = JSON.stringify(Object.fromEntries(ns.getOwnedSourceFiles().map(sf => [sf.n, sf.lvl]))); } catch { }
        if (ns.read("/Temp/owned-source-files.txt") != result) await ns.write("/Temp/owned-source-files.txt", result, 'w')
Ensure you have sufficient free RAM to run this temporary script.

**Comment by alainbryden** [comment]
Indeed 32 gb is probably not enough to run everything. Until you have
doubed it, you should check you active scripts tab and turn off some of the
persistent scripts you don't need yet (like stockmaster and summary scripts)
