### ISSUE TITLE
contractor solveing

### ISSUE THREAD

**Issue by samohtGTO** [alainbryden/bitburner-scripts#291]
A bunch of contracts are unsolveable

**Comment by alainbryden** [comment]
Going to need more details. Even on the latest beta version of the game (https://bitburner-official.github.io/bitburner-src/) all contracts are being solved save for the odd "Find all valid math expressions" due to a game-bug that's expecting "null" not accepting an empty array even though it should - which has been reported to the game dev at https://discord.com/channels/415207508303544321/415213413745164318
