### ISSUE TITLE
Ascend Without TIX API liquidate error

### ISSUE THREAD

**Issue by RaincastWillow** [alainbryden/bitburner-scripts#311]
If autopilot.js tries to ascend without the player owning TIX API, stockmaster fails to liquidate stocks and all scripts stop.
> ERROR: Cannot liquidate stocks because we do not have Tix Api Access

Prevents auto-ascend until player can afford (and manually purchases) stock market access.

**Comment by RaincastWillow** [comment]
I should note that this doesn't just stop ascension, but completely halts progress until the player intervenes. In these cases the script is trying to liquidate stocks before the player could have possibly purchased them, so the check should be ignored and the script should go ahead with ascension.

**Comment by samohtGTO** [comment]
i think i can creat that

**Comment by alainbryden** [comment]
@RaincastWillow I know it's been a while, but by any chance do you have a game save that reproduces this issue?

I tried altering my game such that I no longer have SF 8, and therefore no longer start with WSE / TIX access, but even then why I ascend the script works without issues.

The only way I could reproduce this issue is if I **manually** bought WSE access and **manually** bought stocks, and then tried to ascend. At this point the scripts saw that I have stocks to be sold, but did not have the API access to sell them, triggering an error it couldn't recover from.

By any chance do you recall if you manually bought stocks in this way?

**Comment by alainbryden** [comment]
I have another theory which has to do with a long-standing issue where temporary memory persists between bitnodes - so if you had TIX access in one bitnode, destroyed it, and started in another without TIX access, the helpers.js instance (which caches stock symbols) may still have these in global memory for the next bitnode, even though the scripts are all killed and restarted.

I've worked around this by explicitly checking for TIXAPI Access in ascend.js rather than assuming having stock symbols was an indication.

**Comment by alainbryden** [comment]
The above behaviour was also the root cause of https://github.com/alainbryden/bitburner-scripts/issues/304 so that must be it.
I'm going to have to rethink the use of a cache in helpers.js
