### ISSUE TITLE
daemon.js: Appears to be using hacknet servers even when disabled.

### ISSUE THREAD

**Issue by Spote1990** [alainbryden/bitburner-scripts#317]
I am uncertain of the cause, but the daemon is using hacknet servers for ram regardless of the true or false statement in the settings. Is there a way to disable daemon targeting hacknet servers as a temp fix? Bitnode 9 seems to stall hard if there isn't any hashes moving forward.

**Comment by Spote1990** [comment]
Also, Work for factions also doesn't work with bladeburner, it forces actions despite being checked.

**Comment by herrxyz** [comment]
additional, sometimes the script uses only a few available servers (like "CSEC", but ignores "n00dles") - seems random to me.
seems to happen when I used infiltration script to get like 13b at once (all stats low except hacking) - happened before SF4

**Comment by alainbryden** [comment]
> I am uncertain of the cause, but the daemon is using hacknet servers for ram regardless of the true or false statement in the settings. Is there a way to disable daemon targeting hacknet servers as a temp fix? Bitnode 9 seems to stall hard if there isn't any hashes moving forward.

@Spote1990 I know it's been over a year since you reported this, but if you happen to have a copy of your save file in which this is occurring, it would help.

From my reading of the code, it quite clearly filters out any hostname starting with "hacknet-server-" - and it does this by default unless you override it with "-n" or "--use-hacknet-servers". Double check that you don't have a daemon.js.config.txt file on your system which is overriding this consistently by default.

Note that the HUD will show "(excluding hacknet servers)" on hover if nothing is using RAM on any hacknet servers. If see this, you can be sure they're being left alone:
![image](https://github.com/user-attachments/assets/b105231c-24a0-430e-adee-5582490f1e65)

The only other thing I can think of is that maybe you didn't realize that several scripts use `spend-hacknet-hashes.js` to make purchases, so the number of hashes doesn't typically have a chance to build up.
