### ISSUE TITLE
Feature: Auto install Augmentations

### ISSUE THREAD

**Issue by calpa** [alainbryden/bitburner-scripts#33]
TODO: Install Augmentations when the situation is suitable.

https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.installaugmentations.md

**Comment by raziel420** [comment]
Just a suggestion, while doing this, maybe a fallback for the script for pre-source 4?

**Comment by alainbryden** [comment]
Agreed that this has been something I've been thinking about for a long time, but there are lots of problems to solve before this can be done automatically without screwing the player over.

Long story short, it most definitely has to be an "opt in" (flag to do it, like --purchase) and we probably want it to do a few other things:
- At a certain point, it makes more sense to purchase other things before e.g. adding just one more neuroflux level, such as Home computer RAM and CPUs, sleeve augmentations, gang equipment, buying back company stock. These things all persist after augmentation, but our cash does not, so we shouldn't isntall unless we're positive there's nothing left to put our cash towards.
- We may be *this close* to getting enough faction reputation to unlock donations next round, or earning enough rep for one more important augmentation. What is our threshold for holding off on installing augmentations so that we can finish gaining reputation?

**Comment by alainbryden** [comment]
@raziel420 what sort of thing do you have in mind? I don't think there's anything that can be done pre SF4. Not without hard-coding all the augmentation data that the script currently uses SF4 to retrieve.

**Comment by calpa** [comment]
I think the minimal visible product is to once X (10) augmentations is purchased, then install the augmentations.

**Comment by raziel420** [comment]
Maybe a temp file for a generalized path to at least beat the first run?  The failure of the purchase generation script also causes a failure of the faction work script as well, meaning manual crime/faction/work the entire first run.

Once you can choose a node to run you can hop over to 4 and slog your way to automating the rest.

**Comment by alainbryden** [comment]
@raziel420  I'm not sure what you mean... there's no way to automate crime/faction/work unless you have SF4...

**Comment by alainbryden** [comment]
> I think the minimal visible product is to once X (10) augmentations is purchased, then install the augmentations.

Perhaps this and a few other low-hanging fruit like selling off stock first? That's a big one.

**Comment by calpa** [comment]
@alainbryden Maybe we can start something simple first, and add the other functions later?

For now, the scripts will hang and run forever without purchase augmentations and install augmentations in SF 4.1...

**Comment by Mikek05** [comment]
Just a couple of raw thoughts:
- "Recovery time" parameter calculation. I.e., the time to restore approximately the same average level after reloading. 
- Together with the rate of improvement on the main indicators, this will allow having an estimate at each moment, "the desire to reload" and compare with the "desire to postpone until the event" (when there will be enough money to buy something, etc.) It's just an approach, roughly the same way competing desires work in our brains.
- Also, it would be great to be able to control the behavior of the daemon with quick commands from the terminal without restarting. I take over the strategy while present, and when I'm gone, let it decide something on its own, though not optimally.

**Comment by rmdi-el** [comment]
Sorry, this is probably a silly newbie offtopic question, but I'm at a loss. I can't understand how does the value assigned at the beginning affect the result if no run options are specified? 
Example:

```
let pctTraining = 0.25; // I changed this
...
const argsSchema = [
    ['training-percentage', 0.20],
...
async function initialize(ns) {
    options = ns.flags(argsSchema);
    pctTraining = options['no-training'] ? 0 : options['training-percentage'];
```

**Comment by alainbryden** [comment]
https://github.com/alainbryden/bitburner-scripts/commit/4b49e8c6527705117d108563f1ffd98e89b508e4
