### ISSUE TITLE
work-for-factions.js: Implement reduced job reputation cost with backdoor

### ISSUE THREAD

**Issue by Maxwelldoug** [alainbryden/bitburner-scripts#350]
When you have a backdoor on a business's server (Say, megacorp) you now get a reduced reputation requirement to get promotions. The script currently uses hardcoded values that do not account for this and will spend a noticeable amount of time working an inferior job despite a promotion being available because of this.

**Comment by alainbryden** [comment]
Note that this new game change will also result in the periodic message:
```
Unexpected 'software' promotion from Junior Software Engineer to "Senior Software Engineer. Promotion logic must be off..."
```
Because there is existing logic to check if a promotion is available, but only for the current job position.

So solve for this enhancement, we'd either need to check for promotions across different job positions, or else use whatever new APIs are presumably available to find out what the next promotion is for a given job.
