### ISSUE TITLE
Stock-Manip-Focus

### ISSUE THREAD

**Issue by Mendenj85** [alainbryden/bitburner-scripts#42]
I'm doing BN8.1, I'm finding that each run when I get to where via your script the ability to purchase SQLInject.exe is doable, it purchases that leaving me without enough money to continue buy stocks, thus leaving me at a stalling point. For now I have disabled the programManager.js and just create them myself (why not farm a small bit of Int exp). Wonder about creating an additional "check" for buying programs to have it wait longer than normal so we don't run out of money to play the market. It's basically leaving me with around 10-20m and doesn't buy any more stocks.

Also noticed the Stock amount on the char overview, stays showing an amount even after all are sold, not sure if that's intended.

**Comment by alainbryden** [comment]
That's a fair point. We should add a check to daemon.js that doesn't invoke
program manager, RAM manager, or host manager at all in BN8, or anywhere
hack income is disabled

**Comment by Mendenj85** [comment]
Do you think actually buying and using hacknet servers would also be beneficial? gives you more servers with much more ram and cores to run some threads, would be good in BN8 for stock manip, and possibly 13 for staneks? (although I haven't touched 13 myself yet)

I ran daemon with --stock-manipulation-focus -n -v, but the script won't buy any more servers due to no profits

**Comment by alainbryden** [comment]
Stock manipulation is actually quite immaterial until end-of-BN when your hack level is high and you can execute it dozens or hundreds of times a minute, due to the low probability of actually manipulating.

I think until you have enough cash that you can own the maximum short or long position in every stock, you're better off not spending money on anything else.

I also haven't played BN13, so I have no notion of whether it has something that can influence BN8, which is otherwise designed such that nothing but stocks matter.

**Comment by s6s8** [comment]
https://www.reddit.com/r/Bitburner/comments/rsqffz/bitnode_8_stockmarket_algo_trader_script_without/

This might help.

**Comment by alainbryden** [comment]
I fixed this issue in a recent commit.

**Comment by alainbryden** [comment]
> https://www.reddit.com/r/Bitburner/comments/rsqffz/bitnode_8_stockmarket_algo_trader_script_without/
> 
> This might help.

Appreciate the link, but we're actually well past that. I used the same approach as his first stochastic model, then added logic to detect the probability inversion point, so we almost never lose and can actually get to 4s under 8 hours
