### ISSUE TITLE
Features: Reworked Hash spending

### ISSUE THREAD

**Issue by ShawnPatton** [alainbryden/bitburner-scripts#48]
As I get into new mechanics and find more and more value from the hash options, I'm starting to see a few avenues for better automation.

1. Ability for one instance to spend on multiple options, grabbing the non-money options ASAP, and thus naturally sorting purchases by cost while saving RAM
2. The money option only waits for us to be near capacity if there are other purchase options enabled and we're above a money threshold.
3. Make the arrays for enabled purchase options into global variables, and rework the script start and args so that we can run new instances that just enable purchase options for an existing instance before self-terminating. This then allows any Corporation or Bladeburner scripts we add in the future to tack on their respective boosts as soon as they're relevant.
4. Intelligent server-boosting. If we take the formula for hack level, apply all the multipliers, and scale XP based on RAM, we can take the derivative and solve where it equals some threshold. This will give us a decent estimate of which servers will be accessible before the level plateaus too hard, and we can of course update once the player passes that point. With a reasonable set of targets laid out, we can reduce min security on the strongest one and increase max money on the biggest one that hasn't exceeded 10T (where the diminishing returns kick in).

**Comment by alainbryden** [comment]
I took a decent stab at improving this script to support multiple options.

Note that you can also leave command line arguments "unfulfilled" so you can have a neat alias to use like this:
`boost-server ecorp`
where
`alias boost-server="run spend-hacknet-hashes.js --liquidate --spend-on 'Increase Maximum Money' --spend-on 'Reduce Minimum Security' --spend-on-server "`

While it's a good suggestion, I haven't attempted to implement some sort of global registration of desired purchases because none of my scripts work that way and I don't have infrastructure for it, it's a bit too much of a departure.

What I did do is design it such that multiple versions will not clash with one-another, so you can start and stop instances that have disparate concerns, and they will work about the same, just cost a bit more RAM.

I may later automatically invest in the best server, but as you pointed out it's non-trivial to determine which server will be the money maker before we're ready to ascend, so the onus is on the respective user to fire that up once they think they know.

Feel free to open up a new issue or PR with follow-up suggestions.
