### ISSUE TITLE
faction-manager.js Bladeburner logic

### ISSUE THREAD

**Issue by halandriel** [alainbryden/bitburner-scripts#70]
faction-manager.js should go for all stats not only if in BN 6 or BN 7. Instead it should go for all stats, if the player chose to join Bladburner faction.

Makes some challenges more convenient.

https://github.com/alainbryden/bitburner-scripts/blob/fddb59df1268bb81885b50fa986208d6d877f19a/faction-manager.js#L233 should be 
playerData.inBladeburner ? ['_'] : // If doing bladeburners, combat augs matter too, so just get everything

**Comment by alainbryden** [comment]
Agreed, I was thinking this myself, and will get around to it eventually.

In fact the logic should be `playerData.inBladeburner || playerData.bitNodeN == 6 || playerData.bitNodeN == 7` - because the latter two still have a special case that you know before they've even reached 100 of each combat stat that that's where things are headed (assuming they ascend once before unlocking BB)
