### ISSUE TITLE
work-for-factions desired-stats

### ISSUE THREAD

**Issue by thechad24** [alainbryden/bitburner-scripts#93]
I am incredibly new to coding. The desired-stats flag is looking for an array of various inputs like str, def, dex, agi. But I am confused about how to set the amount. Object keys?

run work-for-factions --desired-stats ...?

Thanks

**Comment by alainbryden** [comment]
Hey, you have to specify the argument multiple times, the in-game arg parser combines them into an array.

So
`run work-for-factions --desired-stats str --desired-stats agi --desired-stats def 
--desired-stats dex`
If you want to only buy augs with any of those 4 stats

**Comment by thechad24** [comment]
Thanks for replying and thanks for the clarification. I also was wondering if there was a way to limit before moving on. For example end when you hit 80 str and 80 def

**Comment by alainbryden** [comment]
`work-for-factions` isn't concerned with training you (doing crime) just for the sake of training you - it is only training you so that you can meet the minimum combat requirements to get into a faction of interest.

If the next faction it wants to join requires 100 of each stat, and it thinks it can train to that in a sensible amount of time, then it will train all the way to 100. If the faction after that requires 200 of each stat, and it thinks that will take too long, it won't spend a second training and will move on to some other faction.

There is a setting `training-stat-per-multi-threshold` which defaults to a value of `100`. This basically says, with default str/str_exp multis of 1, it will only attempt to train you up to 100 str, anything else will probably take too much time. Once you get some augs boosting your stats (e.g. 2.0 str * 2.0 exp = 4.0) then it'll be willing to try and train up to 400, etc...

You can set the `training-stat-per-multi-threshold` to a lower value (like 80 in your case), but what that really means is that if you are currently at 30 of each stat, and the next faction requires 100 of each stat, it won't train up to 80, it'll just skip that faction and you'll be stuck at 30 of each stat.

Hope that makes sense.

If you just want to do crime for the sake of training up stats (or income), don't use `work-for-factions.js` and instead use `crime.js`

**Comment by thechad24** [comment]
Now that I think about it. Doing it by max number wouldn't make any sense in work-for-factions. Having set requirements for factions does. 

I appreciate you taking the time for helping me out.
